import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "@/auth/AuthProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { ViewTransitions } from 'next-view-transitions';
import { NavigationManager } from '@/components/layouts/NavigationManager';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html lang="en">
        <head>
          <link rel="manifest" href="/manifest.json" />
          <meta name="theme-color" content="#000000" />
        </head>
        <body className="antialiased">
          <NavigationManager />
          <AuthProvider>{children}</AuthProvider>
        </body>
      </html>
    </ViewTransitions>
  );
}